### ISSUE TITLE
djpaddle_sync_plans_from_paddle errors out with Paddle error 107 - You don't have permission to access this resource

### ISSUE THREAD

**Issue by denibertovic** [paddle-python/dj-paddle#41]
dj-paddle version: 0.1.2

```
user@b52850d97f85:/app$ ./manage.py djpaddle_sync_plans_from_paddle
Traceback (most recent call last):
  File "/app/./manage.py", line 22, in <module>
    main()
  File "/app/./manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.10/site-packages/djpaddle/management/commands/djpaddle_sync_plans_from_paddle.py", line 16, in handle
    for plan_data in Plan.api_list():
  File "/usr/local/lib/python3.10/site-packages/djpaddle/models.py", line 55, in api_list
    return paddle_client.list_plans()
  File "/usr/local/lib/python3.10/site-packages/paddle/_plans.py", line 19, in list_plans
    return self.post(url=url)
  File "/usr/local/lib/python3.10/site-packages/paddle/paddle.py", line 182, in post
    return self.request(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/paddle/paddle.py", line 154, in request
    raise PaddleException(response_json['error'])
paddle.paddle.PaddleException: Paddle error 107 - You don't have permission to access this resource
```

I'm trying to test paddle integration with the sandbox environment. I have set the DJPADDLE_VENDOR_ID, DJ_PADDLE_API_KEY (the default one already created in the sandbox), DJPADDLE_PUBLIC_KEY  with values from the sandbox-vendors.paddle.com. I've also set DJPADDLE_SANDBOX=True.

**Comment by saschwarz** [comment]
@denibertovic I had to install from git instead of latest package: https://github.com/paddle-python/dj-paddle/issues/35

**Comment by denibertovic** [comment]
Thanks @saschwarz that did the trick! I'm fine closing this but really there ought to be another release cause this will keep happening.
